---
engines:
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "**.coffee"
    - "**.js"
    - "**.jsx"
exclude_paths:
  - node_modules/**/*
  - spec/**/*
