language: node_js
node_js:
  - "stable"
  - "5.0"

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm test
  - codeclimate-test-reporter < ./coverage/lcov.info

services:
  - mongodb

notifications:
  email: false